import React, { useState, useRef } from 'react'
import { QrReader } from 'react-qr-reader'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'

function ScanOverlay() {
  return (
    <>
      <svg viewBox='0 0 100 100' className='top-0 left-0 z-10 absolute w-full h-full p-8'>
        <path fill='none' d='M13,0 L0,0 L0,13' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
        <path fill='none' d='M0,87 L0,100 L13,100' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
        <path
          fill='none'
          d='M87,100 L100,100 L100,87'
          stroke='rgba(255, 0, 0, 0.5)'
          strokeWidth='5'
        />
        <path fill='none' d='M100,13 L100,0 87,0' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
      </svg>
    </>
  )
}

export default function Scan() {
  const router = useRouter()
  const [data, setData] = useState('No result')
  const [showModal, setShowModal] = useState(false)
  const qrRef = useRef(null)

  const handleScan = (result, error) => {
    if (!!result) {
      setData(result?.text)
      setShowModal(true)
      qrRef.current.stop()
    }

    if (!!error) {
      console.info(error)
    }
  }

  const handleCloseModal = () => {
    setShowModal(false)
    router.reload()
  }

  const handleOK = async () => {
    await axios.post(`/api/postData`, { data })
    router.reload()
  }

  return (
    <>
      <Head>
        <title>QR Scan</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col mt-[5rem] justify-center items-center'>
        <div className='flex flex-col justify-center items-center'>
          <h1 className='text-4xl font-bold mb-4'>QR Scanner for Nextjs</h1>
          <div>
            <QrReader
              delay={1000}
              className='w-96 h-96'
              //   className='lg:h-[400px] lg:w-[400px] h-[300px] w-[300px]'
              onResult={handleScan}
              constraints={{ facingMode: 'environment' }}
              ViewFinder={ScanOverlay}
              ref={qrRef}
            />
          </div>
          깃헙 소스:{' '}
          <Link href='https://github.com/nukrobzero/qr-code-scanner-next-js'>
            https://github.com/nukrobzero/qr-code-scanner-next-js
          </Link>
          <Link href={`/`} className='btn btn-primary text-lg'>
            돌아가기
          </Link>
          {showModal && (
            <div className='fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center'>
              <div className='bg-white rounded-md p-4'>
                <p className='text-xl font-bold mb-2'>Scanned data:</p>
                <p>{data}</p>
                <button
                  className='bg-gray-200 text-gray-800 px-4 py-2 rounded-md mt-4 hover:bg-gray-300'
                  onClick={handleCloseModal}
                >
                  Close
                </button>
                <button
                  className='bg-gray-200 text-gray-800 px-4 py-2 rounded-md mx-4 mt-4 hover:bg-gray-300'
                  onClick={handleOK}
                >
                  Ok
                </button>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  )
}
