import React, { useState } from 'react'
import { QrReader } from 'react-qr-reader'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'

const ScanOverlay = () => (
  <svg
    viewBox='0 0 100 100'
    className='top-0 left-0 z-10 absolute w-full h-full border-[50px] border-neutral-900/30'
  >
    <path fill='none' d='M13,0 L0,0 L0,13' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
    <path fill='none' d='M0,87 L0,100 L13,100' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
    <path fill='none' d='M87,100 L100,100 L100,87' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
    <path fill='none' d='M100,13 L100,0 87,0' stroke='rgba(255, 0, 0, 0.5)' strokeWidth='5' />
  </svg>
)

export default function Scan() {
  const [selected, setSelected] = useState('environment')
  const [startScan, setStartScan] = useState(false)
  const [data, setData] = useState('결과 값 없음')

  const handleScan = (result, error) => {
    if (result) {
      setData(result?.text)
      setStartScan(false) // 스캔 완료 후 스캔 종료
    }

    if (error) {
      console.info(error)
    }
  }

  return (
    <>
      <Head>
        <title>QR Scan</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col mt-[5rem] justify-center items-center'>
        <div className='flex flex-col justify-center items-center gap-4'>
          <h1 className='text-4xl font-bold mb-4'>QR Scanner for Nextjs</h1>
          <h2>현재 카메라: {selected}</h2>
          <div>
            {startScan && (
              <>
                <select onChange={(e) => setSelected(e.target.value)}>
                  <option value='environment'>후면 카메라</option>
                  <option value='user'>전면 카메라</option>
                </select>
                <QrReader
                  facingMode={selected}
                  delay={1000}
                  className='w-96 h-96'
                  onResult={handleScan}
                  constraints={{ facingMode: selected }}
                  ViewFinder={ScanOverlay}
                />
              </>
            )}
          </div>

          <button onClick={() => setStartScan(!startScan)} className='btn text-lg'>
            {startScan ? '스캔하는 중..' : '스캔하기'}
          </button>
          {data && <p>{data}</p>}

          <Link href='/' className='btn btn-ghost text-lg mt-8'>
            돌아가기
          </Link>
        </div>
      </main>
    </>
  )
}
